// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using osb.Data;

#nullable disable

namespace osb.Data.Migrations
{
    [DbContext(typeof(OsbDbContext))]
    [Migration("20261008011401_FixEarlyShowcaseDates")]
    partial class FixEarlyShowcaseDates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("BeatmapsetTags", b =>
                {
                    b.Property<int>("BeatmapsetsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("BeatmapsetsId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("BeatmapsetTags");
                });

            modelBuilder.Entity("OsuUserRoles", b =>
                {
                    b.Property<int>("MembersId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RolesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MembersId", "RolesId");

                    b.HasIndex("RolesId");

                    b.ToTable("OsuUserRoles");
                });

            modelBuilder.Entity("SubmissionTags", b =>
                {
                    b.Property<int>("ShowcaseSubmissionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SuggestedTagsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ShowcaseSubmissionId", "SuggestedTagsId");

                    b.HasIndex("SuggestedTagsId");

                    b.ToTable("SubmissionTags");
                });

            modelBuilder.Entity("osb.Data.Beatmapset", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ChangedOnSiteAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("HostId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Medium")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("ShowcasedOn")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("SubmittedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoUrl")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HostId");

                    b.HasIndex("ShowcasedOn");

                    b.ToTable("Beatmapsets");
                });

            modelBuilder.Entity("osb.Data.BeatmapsetStoryboarder", b =>
                {
                    b.Property<int>("BeatmapsetId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OsuUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.HasKey("BeatmapsetId", "OsuUserId");

                    b.HasIndex("OsuUserId");

                    b.ToTable("BeatmapsetStoryboarders");
                });

            modelBuilder.Entity("osb.Data.CommunityRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Colour")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("Rank")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("osb.Data.Learner", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastActiveAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Learners");
                });

            modelBuilder.Entity("osb.Data.OsuUser", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCommunityMember")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("osb.Data.ShowcaseRemoval", b =>
                {
                    b.Property<int>("BeatmapsetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RemovedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("RemovedById")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RemovedByUsername")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("BeatmapsetId");

                    b.ToTable("ShowcaseRemovals");
                });

            modelBuilder.Entity("osb.Data.ShowcaseSubmission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("BeatmapSubmittedOn")
                        .HasColumnType("TEXT");

                    b.Property<int>("BeatmapsetId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HostId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HostUsername")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Medium")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("OsuListsStoryboard")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("OutcomeSeen")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReviewNote")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReviewerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReviewerUsername")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("SubmitterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubmitterUsername")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoUrl")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BeatmapsetId")
                        .IsUnique()
                        .HasFilter("\"Status\" = 0");

                    b.HasIndex("Status");

                    b.HasIndex("SubmitterId");

                    b.ToTable("Submissions");
                });

            modelBuilder.Entity("osb.Data.StoryboardTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("osb.Data.SubmissionCredit", b =>
                {
                    b.Property<int>("SubmissionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OsuUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("SubmissionId", "OsuUserId");

                    b.ToTable("SubmissionCredits");
                });

            modelBuilder.Entity("osb.Data.UnitCompletion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("LearnerId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxScore")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UnitId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LearnerId", "UnitId")
                        .IsUnique();

                    b.ToTable("UnitCompletions");
                });

            modelBuilder.Entity("BeatmapsetTags", b =>
                {
                    b.HasOne("osb.Data.Beatmapset", null)
                        .WithMany()
                        .HasForeignKey("BeatmapsetsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("osb.Data.StoryboardTag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OsuUserRoles", b =>
                {
                    b.HasOne("osb.Data.OsuUser", null)
                        .WithMany()
                        .HasForeignKey("MembersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("osb.Data.CommunityRole", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SubmissionTags", b =>
                {
                    b.HasOne("osb.Data.ShowcaseSubmission", null)
                        .WithMany()
                        .HasForeignKey("ShowcaseSubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("osb.Data.StoryboardTag", null)
                        .WithMany()
                        .HasForeignKey("SuggestedTagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("osb.Data.Beatmapset", b =>
                {
                    b.HasOne("osb.Data.OsuUser", "Host")
                        .WithMany("HostedBeatmapsets")
                        .HasForeignKey("HostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Host");
                });

            modelBuilder.Entity("osb.Data.BeatmapsetStoryboarder", b =>
                {
                    b.HasOne("osb.Data.Beatmapset", "Beatmapset")
                        .WithMany("Storyboarders")
                        .HasForeignKey("BeatmapsetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("osb.Data.OsuUser", "User")
                        .WithMany("Storyboards")
                        .HasForeignKey("OsuUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Beatmapset");

                    b.Navigation("User");
                });

            modelBuilder.Entity("osb.Data.SubmissionCredit", b =>
                {
                    b.HasOne("osb.Data.ShowcaseSubmission", "Submission")
                        .WithMany("Storyboarders")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("osb.Data.UnitCompletion", b =>
                {
                    b.HasOne("osb.Data.Learner", "Learner")
                        .WithMany("Completions")
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Learner");
                });

            modelBuilder.Entity("osb.Data.Beatmapset", b =>
                {
                    b.Navigation("Storyboarders");
                });

            modelBuilder.Entity("osb.Data.Learner", b =>
                {
                    b.Navigation("Completions");
                });

            modelBuilder.Entity("osb.Data.OsuUser", b =>
                {
                    b.Navigation("HostedBeatmapsets");

                    b.Navigation("Storyboards");
                });

            modelBuilder.Entity("osb.Data.ShowcaseSubmission", b =>
                {
                    b.Navigation("Storyboarders");
                });
#pragma warning restore 612, 618
        }
    }
}
