#nullable enable

using Microsoft.EntityFrameworkCore;

namespace osb.Data;

/// <summary>
/// The site's SQLite database: showcase data, showcase submissions and learner progress.
/// Change the model, then add a migration with <c>dotnet ef migrations add &lt;Name&gt;</c>.
/// Migrations are applied on startup (see Program.cs).
/// </summary>
public class OsbDbContext(DbContextOptions<OsbDbContext> options) : DbContext(options)
{
    public DbSet<OsuUser> Users => Set<OsuUser>();
    public DbSet<CommunityRole> Roles => Set<CommunityRole>();
    public DbSet<StoryboardTag> Tags => Set<StoryboardTag>();
    public DbSet<Beatmapset> Beatmapsets => Set<Beatmapset>();
    public DbSet<BeatmapsetStoryboarder> BeatmapsetStoryboarders => Set<BeatmapsetStoryboarder>();
    public DbSet<Learner> Learners => Set<Learner>();
    public DbSet<UnitCompletion> UnitCompletions => Set<UnitCompletion>();
    public DbSet<ShowcaseSubmission> Submissions => Set<ShowcaseSubmission>();
    public DbSet<SubmissionCredit> SubmissionCredits => Set<SubmissionCredit>();
    public DbSet<ShowcaseRemoval> ShowcaseRemovals => Set<ShowcaseRemoval>();

    protected override void OnModelCreating(ModelBuilder model)
    {
        model.Entity<OsuUser>(user =>
        {
            // osu! user IDs are natural keys, never generated by the database.
            user.Property(u => u.Id).ValueGeneratedNever();
            user.Property(u => u.Username).HasMaxLength(32);
            user.HasIndex(u => u.Username);
            user.HasMany(u => u.Roles).WithMany(r => r.Members).UsingEntity("OsuUserRoles");
            user.Ignore(u => u.PrimaryRole);
        });

        model.Entity<CommunityRole>(role =>
        {
            role.Property(r => r.Name).HasMaxLength(32);
            role.Property(r => r.Colour).HasMaxLength(16);
            role.HasIndex(r => r.Name).IsUnique();
        });

        model.Entity<StoryboardTag>(tag =>
        {
            tag.Property(t => t.Slug).HasMaxLength(48);
            tag.Property(t => t.Name).HasMaxLength(48);
            tag.HasIndex(t => t.Slug).IsUnique();
        });

        model.Entity<Beatmapset>(set =>
        {
            set.Property(s => s.Id).ValueGeneratedNever();
            set.Property(s => s.Title).HasMaxLength(256);
            set.Property(s => s.Artist).HasMaxLength(256);
            set.Property(s => s.Medium).HasMaxLength(32);
            set.Property(s => s.VideoUrl).HasMaxLength(256);
            set.HasIndex(s => s.ShowcasedOn);
            set.HasOne(s => s.Host).WithMany(u => u.HostedBeatmapsets)
                .HasForeignKey(s => s.HostId).OnDelete(DeleteBehavior.Restrict);
            set.HasMany(s => s.Tags).WithMany(t => t.Beatmapsets).UsingEntity("BeatmapsetTags");
            // Computed from Storyboarders; without this EF would map it as a separate relationship.
            set.Ignore(s => s.Credits);
        });

        model.Entity<BeatmapsetStoryboarder>(credit =>
        {
            credit.HasKey(c => new { c.BeatmapsetId, c.OsuUserId });
            credit.HasOne(c => c.Beatmapset).WithMany(s => s.Storyboarders)
                .HasForeignKey(c => c.BeatmapsetId).OnDelete(DeleteBehavior.Cascade);
            credit.HasOne(c => c.User).WithMany(u => u.Storyboards)
                .HasForeignKey(c => c.OsuUserId).OnDelete(DeleteBehavior.Restrict);
        });

        model.Entity<Learner>(learner =>
        {
            learner.Property(l => l.Id).ValueGeneratedNever();
            learner.Property(l => l.Username).HasMaxLength(32);
        });

        model.Entity<UnitCompletion>(completion =>
        {
            completion.Property(c => c.UnitId).HasMaxLength(128);
            completion.HasIndex(c => new { c.LearnerId, c.UnitId }).IsUnique();
            completion.HasOne(c => c.Learner).WithMany(l => l.Completions)
                .HasForeignKey(c => c.LearnerId).OnDelete(DeleteBehavior.Cascade);
        });

        model.Entity<ShowcaseSubmission>(submission =>
        {
            submission.Property(s => s.Title).HasMaxLength(256);
            submission.Property(s => s.Artist).HasMaxLength(256);
            submission.Property(s => s.HostUsername).HasMaxLength(32);
            submission.Property(s => s.Medium).HasMaxLength(32);
            submission.Property(s => s.VideoUrl).HasMaxLength(256);
            submission.Property(s => s.Note).HasMaxLength(1000);
            submission.Property(s => s.SubmitterUsername).HasMaxLength(32);
            submission.Property(s => s.ReviewerUsername).HasMaxLength(32);
            submission.Property(s => s.ReviewNote).HasMaxLength(1000);
            submission.HasIndex(s => s.SubmitterId);
            submission.HasIndex(s => s.Status);
            // Only one submission per beatmapset can be waiting for review at a time.
            submission.HasIndex(s => s.BeatmapsetId).IsUnique().HasFilter($"\"Status\" = {(int)SubmissionStatus.Pending}");
            submission.HasMany(s => s.SuggestedTags).WithMany().UsingEntity("SubmissionTags");
            // Computed from Storyboarders, like Beatmapset.Credits.
            submission.Ignore(s => s.Credits);
        });

        model.Entity<SubmissionCredit>(credit =>
        {
            credit.HasKey(c => new { c.SubmissionId, c.OsuUserId });
            credit.Property(c => c.Username).HasMaxLength(32);
            credit.HasOne(c => c.Submission).WithMany(s => s.Storyboarders)
                .HasForeignKey(c => c.SubmissionId).OnDelete(DeleteBehavior.Cascade);
        });

        model.Entity<ShowcaseRemoval>(removal =>
        {
            removal.HasKey(r => r.BeatmapsetId);
            removal.Property(r => r.BeatmapsetId).ValueGeneratedNever();
            removal.Property(r => r.RemovedByUsername).HasMaxLength(32);
            removal.Property(r => r.Reason).HasMaxLength(1000);
        });
    }
}
