// Frontend build: bundles Scripts/ into wwwroot/js with esbuild and copies the self-hosted fonts
// into wwwroot/fonts. Tailwind (Styles/app.css -> wwwroot/css/app.css) runs right after this, see
// the "build" script in package.json. `dotnet build` runs `npm run build` for you.
//
//   node Scripts/build.mjs           one-off build (minified)
//   node Scripts/build.mjs --watch   rebuild JavaScript on change (pair with `npm run watch:css`)

import * as esbuild from 'esbuild';
import { copyFile, mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';

const root = path.resolve(import.meta.dirname, '..');
const watch = process.argv.includes('--watch');
const out = (...parts) => path.join(root, 'wwwroot', ...parts);

// Variable fonts from @fontsource-variable. Each CSS file has one @font-face per Unicode subset,
// so browsers only download the subsets a page actually uses.
const fontFaces = [
    { pkg: '@fontsource-variable/open-sans', css: ['index.css', 'wght-italic.css'] },
    { pkg: '@fontsource-variable/exo-2', css: ['index.css'] },
    { pkg: '@fontsource-variable/jetbrains-mono', css: ['index.css'] },
];

async function buildFonts() {
    await rm(out('fonts'), { recursive: true, force: true });
    await mkdir(out('fonts'), { recursive: true });
    await mkdir(out('css'), { recursive: true });

    let fontsCss = '/* Generated by Scripts/build.mjs from @fontsource-variable packages (SIL Open Font License). */\n';
    for (const { pkg, css } of fontFaces) {
        const pkgDir = path.join(root, 'node_modules', pkg);
        for (const file of css) {
            const source = await readFile(path.join(pkgDir, file), 'utf8');
            fontsCss += source.replace(/url\(\.\/files\/([^)]+)\)/g, (_, name) => `url(/fonts/${name})`);
            for (const [, name] of source.matchAll(/url\(\.\/files\/([^)]+)\)/g))
                await copyFile(path.join(pkgDir, 'files', name), out('fonts', name));
        }
    }
    await writeFile(out('css', 'fonts.css'), fontsCss);
}

const jsOptions = {
    absWorkingDir: root,
    entryPoints: {
        site: 'Scripts/site.js',
        learn: 'Scripts/learn.js',
        'script-worker': 'Scripts/storyboard/script-worker.js',
    },
    outdir: 'wwwroot/js',
    bundle: true,
    splitting: true,
    format: 'esm',
    target: ['es2022'],
    chunkNames: 'chunks/[name]-[hash]',
    minify: !watch,
    sourcemap: 'linked',
    legalComments: 'linked',
    logLevel: 'info',
};

await buildFonts();

if (watch) {
    const context = await esbuild.context(jsOptions);
    await context.watch();
} else {
    await rm(out('js'), { recursive: true, force: true });
    await esbuild.build(jsOptions);
}
